#!/usr/bin/env python3
"""Compile the RAD GPU compute kernels to SPIR-V and embed them as C headers.

The generated headers under src/sdhlt/sdHLRAD/gpu/spirv/ are committed, so
building ReSDHLT needs no shader compiler and no Vulkan SDK. Run this only
after editing a .comp/.glsl file, and commit the result alongside it.

Usage:
    python scripts/gen_spirv.py [--compiler PATH]

Accepts either glslc (Vulkan SDK, shaderc) or glslang. Looked up on PATH and
under $VULKAN_SDK/bin unless --compiler is given.
"""
import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "src", "sdhlt", "sdHLRAD", "gpu", "shaders")
OUT = os.path.join(ROOT, "src", "sdhlt", "sdHLRAD", "gpu", "spirv")

# (source stem, output stem, symbol, extra defines)
KERNELS = [
    ("trace_bsp", "trace_bsp", "g_trace_bsp_spirv", []),
    ("gather", "gather", "g_gather_spirv", []),
    ("gather", "gather_f32", "g_gather_f32_spirv", ["FLOAT_NORMALIZE"]),
    ("formfactor", "formfactor", "g_formfactor_spirv", []),
]


def find_compiler(explicit):
    if explicit:
        return explicit, os.path.basename(explicit).lower()
    hints = []
    sdk = os.environ.get("VULKAN_SDK")
    if sdk:
        hints.append(os.path.join(sdk, "bin"))
    for name in ("glslc", "glslangValidator", "glslang"):
        found = shutil.which(name)
        if found:
            return found, name.lower()
        for hint in hints:
            for ext in ("", ".exe"):
                cand = os.path.join(hint, name + ext)
                if os.path.isfile(cand):
                    return cand, name.lower()
    sys.exit("no shader compiler found: install the Vulkan SDK, or pass --compiler")


def compile_one(compiler, kind, src, spv, defines):
    if "glslc" in kind:
        cmd = [compiler, "--target-env=vulkan1.0", "-O"]
        cmd += ["-D" + d for d in defines]
        cmd += ["-o", spv, src]
    else:
        cmd = [compiler, "-V", "--target-env", "vulkan1.0", "-I" + SHADERS]
        cmd += ["-D" + d for d in defines]
        cmd += ["-o", spv, src]
    subprocess.run(cmd, check=True, cwd=SHADERS)


def embed(spv, header, symbol):
    data = open(spv, "rb").read()
    if len(data) % 4:
        sys.exit("%s is not a whole number of SPIR-V words" % spv)
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + " ".join("0x%02x," % b for b in data[i:i + 12]))
    with open(header, "w", newline="\n") as f:
        f.write("// Generated by scripts/gen_spirv.py from shaders/%s - do not edit.\n"
                % os.path.basename(spv).replace(".spv", ".comp"))
        f.write("static const unsigned char %s[] = {\n%s\n};\n" % (symbol, "\n".join(rows)))
        f.write("static const unsigned int %s_size = sizeof(%s);\n" % (symbol, symbol))
    return len(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--compiler")
    args = ap.parse_args()
    compiler, kind = find_compiler(args.compiler)
    print("using %s" % compiler)
    os.makedirs(OUT, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        for src_stem, out_stem, symbol, defines in KERNELS:
            src = os.path.join(SHADERS, src_stem + ".comp")
            spv = os.path.join(tmp, out_stem + ".spv")
            compile_one(compiler, kind, src, spv, defines)
            header = os.path.join(OUT, out_stem + "_spirv.h")
            size = embed(spv, header, symbol)
            print("  %-14s -> %s (%d bytes)" % (src_stem + ".comp", os.path.basename(header), size))


if __name__ == "__main__":
    main()
